{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Financials\",\"ProdSales\",\"Feedstock\",\"FACT Data\",\"DIM Series\",\"DIM SeriesType\",\"@RefreshDate\",\"@Measures\",\"@KPI Calc Type\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Financials",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // Source",
          "    Source = Csv.Document(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Key Metrics Dashboard\\Data\\Financials.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    ",
          "    // Clean & Prep",
          "    SetDataTypes = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Series\", type text}, {\"SeriesCategory\", type text}, {\"SeriesUnits\", type text}, {\"SeriesType\", type text}, {\"Value\", Int64.Type}}),",
          "    ScrubNegatives = Table.TransformColumns(SetDataTypes,{{\"Value\", Number.Abs, Int64.Type}}),",
          "    ScrubZeroes = Table.SelectRows(ScrubNegatives, each ([Value] <> 0))",
          "in",
          "    ScrubZeroes"
        ],
        "kind": "m",
        "lineageTag": "7fb751a9-9407-4492-84c9-7e74bd6ddec6",
        "queryGroup": "Source Queries"
      },
      {
        "name": "ProdSales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    ",
          "    // Source",
          "    Source = Csv.Document(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Key Metrics Dashboard\\Data\\ProdSales.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    ",
          "    // Clean & Prep",
          "    SetDataTypes = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Series\", type text}, {\"SeriesCategory\", type text}, {\"SeriesUnits\", type text}, {\"SeriesType\", type text}, {\"Value\", Int64.Type}}),",
          "    ScrubNegatives = Table.TransformColumns(SetDataTypes,{{\"Value\", Number.Abs, Int64.Type}})",
          "in",
          "    ScrubNegatives"
        ],
        "kind": "m",
        "lineageTag": "f274b5a6-7440-4922-adcd-88dcffab41f3",
        "queryGroup": "Source Queries"
      },
      {
        "name": "Feedstock",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    ",
          "    // Source",
          "    Source = Excel.Workbook(File.Contents(\"G:\\My Drive\\JMS Analytics\\Projects\\Key Metrics Dashboard\\Data\\Feedstock.xlsx\"), null, true),",
          "    Data_Sheet = Source{[Item=\"Data\",Kind=\"Sheet\"]}[Data],",
          "    ",
          "    // Clean & Prep",
          "    PromoteHeaders = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),",
          "    RemoveUnnecessaryColumns = Table.SelectColumns(PromoteHeaders,{\"GCE\", \"Activity\", \"Date\"}),",
          "    RemoveUnnecessaryRows = Table.SelectRows(RemoveUnnecessaryColumns, each ([GCE] <> null) and ([Activity] <> null and [Activity] <> \"Inventory\")),",
          "    CreateSeries = Table.AddColumn(RemoveUnnecessaryRows, \"Series\", each Text.Proper([Activity])),",
          "    CreateSeriesCat = Table.AddColumn(CreateSeries, \"SeriesCategory\", each if [Series] = \"Received\" then \"Feedstock In\" else \"Feedstock Out\"),",
          "    CreateSeriesUnits = Table.AddColumn(CreateSeriesCat, \"SeriesUnits\", each \"GCE\"),",
          "    CreateSeriesType = Table.AddColumn(CreateSeriesUnits, \"SeriesType\", each \"Actuals\"),",
          "    RemoveActivity = Table.RemoveColumns(CreateSeriesType,{\"Activity\"}),",
          "    RenameGCE = Table.RenameColumns(RemoveActivity,{{\"GCE\", \"Value\"}}),",
          "    SetDataTypes = Table.TransformColumnTypes(RenameGCE,{{\"Value\", Int64.Type}, {\"Date\", type date}, {\"Series\", type text}, {\"SeriesCategory\", type text}, {\"SeriesUnits\", type text}, {\"SeriesType\", type text}}),",
          "    ScrubNegatives = Table.TransformColumns(SetDataTypes,{{\"Value\", Number.Abs, Int64.Type}})",
          "in",
          "    ScrubNegatives"
        ],
        "kind": "m",
        "lineageTag": "fbfcbb6d-8a91-4d44-8683-02b743cb805e",
        "queryGroup": "Source Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Holds queries that dimensionalize sources into data model",
        "folder": "Model"
      }
    ],
    "relationships": [
      {
        "name": "d43de0f4-f562-4333-9e17-ac8edc70f666",
        "fromColumn": "Series ID",
        "fromTable": "FACT Data",
        "toColumn": "Series ID",
        "toTable": "DIM Series"
      },
      {
        "name": "53c22d8e-85af-42ae-82cf-72e0595a59a6",
        "fromColumn": "SeriesType ID",
        "fromTable": "FACT Data",
        "toColumn": "SeriesType ID",
        "toTable": "DIM SeriesType"
      },
      {
        "name": "36788d15-13a9-4c6e-aff3-c180154c753b",
        "fromColumn": "Date",
        "fromTable": "FACT Data",
        "toColumn": "Date",
        "toTable": "DIM Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "FACT Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Date",
            "formatString": "Short Date",
            "isAvailableInMdx": false,
            "lineageTag": "12dbbdb5-1ea9-416e-9d56-407de09d9156",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "amount (in usd, gallons, gce)",
            "isAvailableInMdx": false,
            "lineageTag": "d389eee3-d32d-44e5-aa2b-d2e58c03c44c",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Series ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Series id",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "fa3061d1-bfe8-4629-8419-fc1ecc4678d7",
            "sourceColumn": "Series ID",
            "summarizeBy": "none"
          },
          {
            "name": "SeriesType ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Series type id",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "dbbc9711-391d-4d6e-9a08-8b3e1f8ab509",
            "sourceColumn": "SeriesType ID",
            "summarizeBy": "none"
          }
        ],
        "description": "fact table",
        "lineageTag": "37a29d7e-31fa-4d5e-9401-f26c4af95c0c",
        "partitions": [
          {
            "name": "FACT Data-0352084a-3554-4853-9a17-bb4b359b72a8",
            "mode": "import",
            "queryGroup": "Model",
            "source": {
              "expression": [
                "let",
                "    ",
                "    // V-Merge",
                "    Source = Table.Combine({Financials, ProdSales, Feedstock}),",
                "    ",
                "    // Dimensionalization",
                "    MergeSeriesFK = Table.NestedJoin(Source, {\"Series\"}, #\"DIM Series\", {\"Series\"}, \"DIM Series\", JoinKind.LeftOuter),",
                "    ExpandSeriesFK = Table.ExpandTableColumn(MergeSeriesFK, \"DIM Series\", {\"Series ID\"}, {\"Series ID\"}),",
                "    MergeSeriesTypeFK = Table.NestedJoin(ExpandSeriesFK, {\"SeriesType\"}, #\"DIM SeriesType\", {\"SeriesType\"}, \"DIM SeriesType\", JoinKind.LeftOuter),",
                "    ExpandSeriesTypeFK = Table.ExpandTableColumn(MergeSeriesTypeFK, \"DIM SeriesType\", {\"SeriesType ID\"}, {\"SeriesType ID\"}),",
                "    RemoveDIMDescrs = Table.RemoveColumns(ExpandSeriesTypeFK,{\"Series\", \"SeriesCategory\", \"SeriesUnits\", \"SeriesType\"})",
                "in",
                "    RemoveDIMDescrs"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM Series",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Series ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "primary key for series",
            "formatString": "0",
            "isAvailableInMdx": false,
            "isHidden": true,
            "isKey": true,
            "lineageTag": "b0381c80-e044-4622-9dbe-3bde8706943f",
            "sourceColumn": "Series ID",
            "summarizeBy": "none"
          },
          {
            "name": "Series",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Name of series or kpy",
            "isAvailableInMdx": false,
            "lineageTag": "9cd37d47-d878-4513-b9db-1f102ac5d834",
            "sourceColumn": "Series",
            "summarizeBy": "none"
          },
          {
            "name": "SeriesCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Category that the series is in (revenue, expenses, retail or feedstock)",
            "isAvailableInMdx": false,
            "lineageTag": "3ac6b8e8-a71e-4748-9f93-5374269c5c8b",
            "sourceColumn": "SeriesCategory",
            "summarizeBy": "none"
          },
          {
            "name": "SeriesUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The units (usd, gallons, etc.) of the series",
            "isAvailableInMdx": false,
            "lineageTag": "e13acc1c-6c49-4f77-8b11-89a1885a3f79",
            "sourceColumn": "SeriesUnits",
            "summarizeBy": "none"
          },
          {
            "name": "SeriesFullName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Full display name of the series for the series selector slicer and SWITCH() statement that controls the trends visual",
            "expression": [
              "",
              "'DIM Series'[SeriesCategory] ",
              "& \": \" ",
              "& 'DIM Series'[Series]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1a57f4b7-0547-40f6-b31d-b525a5739996",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SeriesWithUnits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "The display name for the performance visual, which provides the series and units in parentheses ()",
            "expression": [
              "",
              "'DIM Series'[Series]",
              "& \" (\"",
              "& IF('DIM Series'[SeriesUnits] = \"USD\",\"$\",'DIM Series'[SeriesUnits])",
              "& \")\""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "05e63d5c-1842-484e-bafa-d1476c2e31c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "KPIGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'DIM Series'[Series] IN {\"Type 1\", \"Type 2\"}, \"Total Costs ($)\",",
              "    'DIM Series'[Series] IN {\"Source 1\", \"Source 2\", \"Source 3\"}, \"Total Revenues ($)\",",
              "    'DIM Series'[Series] = \"Production\", \"Production (gal)\",",
              "    'DIM Series'[Series] = \"Processed\", \"Processed (GCE)\",",
              "    \"Not a KPI\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "68bef88c-fea1-4f79-892b-ef4b1bb0fa03",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "description": "Series name dimensions",
        "lineageTag": "297fb86d-2df6-4a47-bd34-b7c317eb9f39",
        "partitions": [
          {
            "name": "DIM Series-e281fd0b-4997-4d52-9c25-b17de740f5a7",
            "mode": "import",
            "queryGroup": "Model",
            "source": {
              "expression": [
                "let",
                "    // V-Merge",
                "    Source = Table.Combine({Financials, ProdSales, Feedstock}),",
                "    ",
                "    // Dimensionalization",
                "    SelectDIMColumns = Table.SelectColumns(Source,{\"Series\", \"SeriesCategory\", \"SeriesUnits\"}),",
                "    CreateUniqueComposites = Table.Distinct(SelectDIMColumns),",
                "    AddPk = Table.AddIndexColumn(CreateUniqueComposites, \"Index\", 1, 1, Int64.Type),",
                "    MakePkFirst = Table.ReorderColumns(AddPk,{\"Index\", \"Series\", \"SeriesCategory\", \"SeriesUnits\"}),",
                "    RenamePk = Table.RenameColumns(MakePkFirst,{{\"Index\", \"Series ID\"}})",
                "in",
                "    RenamePk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM SeriesType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SeriesType ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Primary key for series type",
            "formatString": "0",
            "isAvailableInMdx": false,
            "isHidden": true,
            "isKey": true,
            "lineageTag": "bd380f32-02a9-48ff-80f9-a0c2819ce983",
            "sourceColumn": "SeriesType ID",
            "summarizeBy": "none"
          },
          {
            "name": "SeriesType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Series type description",
            "isAvailableInMdx": false,
            "lineageTag": "8b22fbfd-fb30-42cd-9aae-d98c061894ec",
            "sourceColumn": "SeriesType",
            "summarizeBy": "none"
          }
        ],
        "description": "Series type dimension",
        "lineageTag": "0c9c030e-3406-4af1-be6f-aab9ab96fc1d",
        "partitions": [
          {
            "name": "DIM SeriesType-c409a0c7-9ba8-4f7e-aeaa-11e40f7865f2",
            "mode": "import",
            "queryGroup": "Model",
            "source": {
              "expression": [
                "let",
                "    // V-Merge",
                "    Source = Table.Combine({Financials, ProdSales, Feedstock}),",
                "    ",
                "    // Dimensionalization",
                "    SelectDIMColumn = Source[SeriesType],",
                "    DIMColToTable = Table.FromList(SelectDIMColumn, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    RemoveDups = Table.Distinct(DIMColToTable),",
                "    RenameDIM = Table.RenameColumns(RemoveDups,{{\"Column1\", \"SeriesType\"}}),",
                "    ChangeDIMType = Table.TransformColumnTypes(RenameDIM,{{\"SeriesType\", type text}}),",
                "    AddPk = Table.AddIndexColumn(ChangeDIMType, \"Index\", 1, 1, Int64.Type),",
                "    MakePkFirst = Table.ReorderColumns(AddPk,{\"Index\", \"SeriesType\"}),",
                "    RenamePk = Table.RenameColumns(MakePkFirst,{{\"Index\", \"SeriesType ID\"}})",
                "in",
                "    RenamePk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "@RefreshDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isAvailableInMdx": false,
            "lineageTag": "ea47659b-9f96-4139-9b57-f96e9da1c879",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isAvailableInMdx": false,
            "lineageTag": "750cd61d-3ee7-4d15-91bc-d4d45431c791",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isAvailableInMdx": false,
            "lineageTag": "e6fe90a0-f4ce-4e2b-ad2f-49e8c6b378cd",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bafd21a6-b6ce-489d-9d21-4f0397acd3e4",
        "partitions": [
          {
            "name": "@RefreshDate-1b0612ea-5e7c-4d51-9551-bd078e58a62a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "SummerTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 3, 14), Day.Sunday),",
                "WinterTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 10, 14), Day.Sunday),",
                "",
                "Timezonehours = if DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) < SummerTimeStartDate & #time(1, 0, 0) or",
                "DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) > WinterTimeStartDate & #time(1, 0, 0) then",
                "-8 else -7,",
                "",
                "#\"Date and Time\" = DateTimeZone.SwitchZone(DateTimeZone.UtcNow(), Timezonehours, 0),",
                "",
                "#\"Converted to Table\" = #table(1, {{#\"Date and Time\"}}),",
                "",
                "#\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "",
                "#\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"DateTime\", type datetimezone}}),",
                "",
                "#\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"DateTime\", \"DateTime - Copy\"),",
                "",
                "#\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "",
                "#\"Duplicated Column1\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Date\", \"Date - Copy\"),",
                "",
                "#\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column1\",{{\"Date - Copy\", type time}, {\"Date\", type date}}),",
                "",
                "#\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Date - Copy\", \"Time\"}})",
                "",
                "in",
                "",
                "#\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "45dfa456e21b4a4dbdaf86002c82596a"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "description": "Primary key for date dimension",
            "formatString": "Short Date",
            "isAvailableInMdx": false,
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "3e611ae8-32ca-4db5-a2c8-c8892549a4c4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithData",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Binary indicator used in time intelligence calculations",
            "expression": [
              "",
              "'DIM Date'[Date] <= MAX ('FACT Data'[Date] )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isAvailableInMdx": false,
            "isDataTypeInferred": true,
            "lineageTag": "0cbe5872-0b33-4268-bb5d-a69ef8f33c31",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CompletedMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Binary indicator used in visual-level filters that condition measures on dates for which there is a complete month.",
            "expression": [
              "",
              "EOMONTH('DIM Date'[Date], 0) < TODAY()"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isAvailableInMdx": false,
            "isDataTypeInferred": true,
            "lineageTag": "aab41fcf-0214-4bac-bc62-1e80314fdfda",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "description": "Month and year of the date (text)",
            "formatString": "mmm yyyy",
            "isNameInferred": true,
            "lineageTag": "7236808c-6878-4c51-9042-b91722bd62d6",
            "sortByColumn": "Month Year Code",
            "sourceColumn": "[Month Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Code used to sort the Month and Year categories",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5eb9a468-9dcf-4a4e-a27e-8559d3a7320e",
            "sourceColumn": "[Month Year Code]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYearDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "description": "Month-year (like mm/01/yyyy) of the date",
            "expression": "STARTOFMONTH('DIM Date'[Date])",
            "formatString": "mmm yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "73c2beb2-3638-4c53-a79f-a864362e12a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Fiscal year of the date",
            "expression": [
              "",
              "VAR _FY = IF ( MONTH ( 'DIM Date'[Date] ) <= 6, YEAR ( 'DIM Date'[Date] ), YEAR ( 'DIM Date'[Date] ) + 1 )",
              "RETURN",
              "\"FY \" & _FY"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0c7d0345-cf72-4bb7-a3e3-d68e076bf1f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Slicer Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _LatestDateWithData = ",
              "    CALCULATE(",
              "        MAX('DIM Date'[Date]),",
              "        FILTER ('DIM Date', 'DIM Date'[DateWithData] = TRUE)",
              "    )",
              "RETURN",
              "IF('DIM Date'[Date] = _LatestDateWithData, \"Latest\", FORMAT ( 'DIM Date'[Date], \"mmm yyyy\" ))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8a5fc9f8-c8ac-47f6-84ea-336eb4877d9c",
            "sortByColumn": "Month Year Code",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b810c0cf-62a9-4555-b2bb-5ed8be00349f",
            "sortByColumn": "Year Sort",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "34db929b-9dba-4d51-8336-67c3222df45d",
            "sortByColumn": "Quarter Year Code",
            "sourceColumn": "[Quarter Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Year Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cbc6c564-c4e6-4d66-9f77-0db240d03348",
            "sourceColumn": "[Quarter Year Code]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bc811fdf-cfad-4e6c-8ece-c0d8182b8f49",
            "sourceColumn": "[Year Sort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "description": "DAX-generated date dimension",
        "lineageTag": "dd6382b7-88c7-4c0f-9edc-4c90c47f4428",
        "measures": [
          {
            "name": "ShowValueForDates",
            "description": "Hidden measure used in time intelligence calculations",
            "expression": [
              "",
              "VAR LastDateWithData =",
              "    CALCULATE ( MAX ( 'FACT Data'[Date] ), REMOVEFILTERS() )",
              "VAR FirstDateVisible =",
              "    MIN ( 'DIM Date'[Date] )",
              "VAR Result = FirstDateVisible <= LastDateWithData",
              "RETURN",
              "    Result"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a5576c3d-cc41-477f-9563-a8b24f73b373"
          }
        ],
        "partitions": [
          {
            "name": "DIM Date-55c54b60-493b-4133-88f7-5794b409ca74",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR MinYear = YEAR ( MIN ( 'FACT Data'[Date] ) )",
                "VAR MaxYear = YEAR ( MAX ( 'FACT Data'[Date] ) )",
                "RETURN",
                "ADDCOLUMNS (",
                "    FILTER (",
                "        CALENDARAUTO( ),",
                "        AND ( YEAR ( [Date] ) >= MinYear, YEAR ( [Date] ) <= MaxYear )",
                "    ),",
                "    \"Month Year\", FORMAT ( [Date], \"mmm yyyy\" ),",
                "    \"Month Year Code\", FORMAT ( [Date], \"yyyymm\" ),",
                "    \"Year\", FORMAT ( [Date], \"yyyy\"),",
                "    \"Year Sort\", YEAR ( [Date] ),",
                "    \"Quarter Year\", FORMAT ( [Date], \"q:yyyy\" ),",
                "    \"Quarter Year Code\", FORMAT ( [Date], \"yyyyq\")",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "@Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "faf498cb-5751-4d2f-819b-d0b2ce13dd71",
        "measures": [
          {
            "name": "LastDateForAll",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "MINX (",
              "    SUMMARIZE (",
              "        'DIM Series',",
              "        'DIM Series'[SeriesCategory],",
              "        \"Max Date\", CALCULATE ( MAX ( 'FACT Data'[Date] ), 'FACT Data'[SeriesType ID]=1 )",
              "    ),",
              "    [Max Date]",
              ")"
            ],
            "formatString": "mm/dd/yyyy",
            "lineageTag": "9cae1bec-3bd8-4fcf-9141-a753734cbe5e"
          },
          {
            "name": "TotalActuals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1 Base Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ('FACT Data'[Value] ),",
              "    'DIM SeriesType'[SeriesType] = \"Actuals\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "95b7f122-8fed-4cf0-af6a-cefd4ef3e963"
          },
          {
            "name": "TotalBudget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1 Base Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ('FACT Data'[Value]),",
              "    'DIM SeriesType'[SeriesType] = \"Budget\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "7ce67ff0-1331-4e93-aa0b-00feae13b12f"
          },
          {
            "name": "Actuals12MMA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "2 Moving Aggs",
            "expression": [
              "",
              "VAR NumOfMonths = 12",
              "VAR LastCurrentDate =",
              "    MAX ( 'DIM Date'[Date] )",
              "VAR Period =",
              "    DATESINPERIOD ( 'DIM Date'[Date], LastCurrentDate, - NumOfMonths, MONTH)",
              "VAR Result =",
              "    CALCULATE (",
              "        AVERAGEX (",
              "            VALUES ( 'DIM Date'[Date] ),",
              "            [TotalActuals]",
              "        ),",
              "        Period",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "a645767e-4a53-4c31-a294-f37dedcaac37"
          },
          {
            "name": "TheAlberto",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "INT ( ",
              "    NOT ISEMPTY ( ",
              "        FILTER ( 'FACT Data', 'FACT Data'[SeriesType ID] = 1 ) ",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9cfabbb8-b82a-422d-957e-11150f73cc66"
          },
          {
            "name": "Actuals12MMT",
            "displayFolder": "2 Moving Aggs",
            "expression": [
              "",
              "IF ( ",
              "    [ShowValueForDates], ",
              "    CALCULATE ( ",
              "        [TotalActuals], ",
              "        DATESINPERIOD (",
              "            'DIM Date'[Date],",
              "            MAX ( 'DIM Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    ) ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "7f6abcb6-3270-4f6b-b410-57907b0044fc"
          },
          {
            "name": "Actuals12MMT_Chg",
            "displayFolder": "2 Moving Aggs",
            "expression": [
              "",
              "VAR CurrentMT = '@Measures'[Actuals12MMT]",
              "VAR PreviousMT = CALCULATE( '@Measures'[Actuals12MMT], DATEADD ( 'DIM Date'[Date], -12, MONTH ) )",
              "VAR DiffMT = CurrentMT - PreviousMT",
              "RETURN",
              "    DIVIDE ( DiffMT, PreviousMT, \"ND\" )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f9b91c15-9db6-4293-b1e2-f95f68201d3a"
          },
          {
            "name": "LineChartTitle",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "VAR SelMeasure = SELECTEDVALUE ('DIM Series'[SeriesFullName], \"Multiple Series*\")",
              "VAR SelUnits = SELECTEDVALUE ('DIM Series'[SeriesUnits], \"Various\" )",
              "RETURN",
              "\"Actual trends: \" & SelMeasure & \" \" & \"(\" & SelUnits &\")\""
            ],
            "lineageTag": "b90f0a41-73a5-42fb-bad9-753624a8b31c"
          },
          {
            "name": "LineChartFootnote",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "VAR SelectedSeries = ",
              "CONCATENATEX (",
              "    VALUES ( 'DIM Series' ),",
              "    'DIM Series'[Series] & \" (\" & 'DIM Series'[SeriesUnits] & \")\",",
              "    \", \"",
              ")",
              "RETURN",
              "IF (",
              "    HASONEVALUE('DIM Series'[SeriesFullName]),\"\",",
              "    \"* Combining \" & SelectedSeries",
              ")"
            ],
            "lineageTag": "c14d07bb-eb9e-4272-8b76-17012d3407f3"
          },
          {
            "name": "TotalActualsPY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "1 Base Measures",
            "expression": [
              "",
              "IF (",
              "    [ShowValueForDates],",
              "    CALCULATE (",
              "        [TotalActuals],",
              "        CALCULATETABLE ( ",
              "            DATEADD ( 'DIM Date'[Date], -1, YEAR ),",
              "            'DIM Date'[DateWithData] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "576ca87e-d785-4f53-9160-e1cfb349e905"
          },
          {
            "name": "ActualsFYTD",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "    CALCULATE(",
              "        [TotalActuals],",
              "        DATESYTD ( 'DIM Date'[Date], \"6-30\")",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "be5f37ed-8bab-423d-8b91-000dfe95d9ef"
          },
          {
            "name": "ActualsPFYTD",
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "CALCULATE(",
              "    [ActualsFYTD],",
              "    DATEADD ('DIM Date'[Date], -12, MONTH )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "eeab4fa1-1ee7-4534-bde7-0d131f58a3a5"
          },
          {
            "name": "BudgetFYTD",
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "    CALCULATE(",
              "        [TotalBudget],",
              "        DATESYTD ( 'DIM Date'[Date], \"6-30\")",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "a4d92891-b8a1-469c-826f-fef90433ac59"
          },
          {
            "name": "ActualsFYTD_Chg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "VAR CurrentFY = [ActualsFYTD]",
              "VAR PreviousFY = [ActualsPFYTD]",
              "VAR Diff = CurrentFY - PreviousFY",
              "RETURN",
              "    DIVIDE ( Diff, PreviousFY, \"ND\" )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f6f5c0ae-be18-4abe-b9b4-f52e96000419"
          },
          {
            "name": "ActualsCYTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "IF(",
              "    [ShowValueForDates],",
              "    CALCULATE(",
              "        [TotalActuals],",
              "        DATESYTD ( 'DIM Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "76332163-bc53-4a46-a239-e10ac7881214"
          },
          {
            "name": "AC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1 Base Measures",
            "expression": [
              "",
              "SWITCH([Selected Calc],",
              "    1, [ActualsCYTD],",
              "    2, [Actuals12MMT]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c001ddad-ec42-4898-a264-6afff056ed9c"
          },
          {
            "name": "PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1 Base Measures",
            "expression": [
              "",
              "SWITCH([Selected Calc],",
              "    1, [ActualsCYTD_PY],",
              "    2, [Actuals12MMT_PY]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "a089f65f-2065-4b20-814d-a83fde81f950"
          },
          {
            "name": "ActualsCYTD_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "3 Year To Date",
            "expression": [
              "",
              "IF (",
              "    [ShowValueForDates],",
              "    CALCULATE (",
              "        [ActualsCYTD],",
              "        CALCULATETABLE ( ",
              "            DATEADD ( 'DIM Date'[Date], -1, YEAR ),",
              "            'DIM Date'[DateWithData] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "07852761-86eb-4c3f-b904-ce13b8635cba"
          },
          {
            "name": "Max Date Actuals",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('FACT Data'[Date]),",
              "    'FACT Data'[SeriesType ID]=1",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "5ee2a508-fe0d-4758-a682-4cc9e10bc958"
          },
          {
            "name": "Actuals12MMT_PY",
            "displayFolder": "2 Moving Aggs",
            "expression": [
              "",
              "IF(",
              "    [ShowValueForDates],",
              "    CALCULATE(",
              "        [Actuals12MMT],",
              "        DATEADD('DIM Date'[Date], -1, YEAR)",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "29e487c9-c39f-4217-b34f-7e11e6891ba0"
          },
          {
            "name": "DynamicMovingAvg",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2 Moving Aggs",
            "expression": [
              "",
              "VAR _Periods = SELECTEDVALUE('@MA Periods'[@MA Periods])",
              "RETURN",
              "SWITCH (",
              "    SELECTEDVALUE( '@DT Granularity'[Granularity] ),",
              "    \"Year\", CALCULATE( [TotalActuals], DATESINPERIOD( 'DIM Date'[Date], LASTDATE( 'DIM Date'[Date]), -_Periods, YEAR ) ) / _Periods,",
              "    \"Quarter\", CALCULATE( [TotalActuals], DATESINPERIOD( 'DIM Date'[Date], LASTDATE( 'DIM Date'[Date] ), -_Periods, QUARTER ) ) / _Periods,",
              "    \"Month\", CALCULATE( [TotalActuals], DATESINPERIOD( 'DIM Date'[Date], LASTDATE( 'DIM Date'[Date]), -_Periods, MONTH ) ) / _Periods,",
              "    \"Date\", CALCULATE( [TotalActuals], DATESINPERIOD( 'DIM Date'[Date], LASTDATE( 'DIM Date'[Date] ), -_Periods, DAY ) ) / _Periods,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "51af4122-143f-43d4-90db-658414f3f190"
          },
          {
            "name": "LastActual",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "VAR _LastDate = MAX('FACT Data'[Date])",
              "RETURN",
              "\"Last actual: \"&FORMAT(_LastDate, \"mmm d yyyy\")"
            ],
            "lineageTag": "0a329dec-a6d4-4731-ad1c-a7fe3d2d5c9d"
          },
          {
            "name": "MA Legend Text",
            "displayFolder": "Labels, Text & Formatting",
            "expression": [
              "",
              "VAR _SelGranularity = SELECTEDVALUE('@DT Granularity'[Granularity])",
              "VAR _SelPeriods = SELECTEDVALUE('@MA Periods'[@MA Periods])",
              "VAR _Result = ",
              "_SelPeriods &",
              "\" \"&",
              "SWITCH (",
              "    _SelGranularity,",
              "    \"Date\", \"Day\",",
              "    _SelGranularity",
              ") &",
              "\" moving avg.\"",
              "",
              "RETURN _Result"
            ],
            "lineageTag": "fd0b35f9-514c-4351-9d0a-5d45516ef6f1"
          }
        ],
        "partitions": [
          {
            "name": "@Measures-310e548f-59c6-4e3b-ae9d-d29c0e3076b6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "@KPI Calc Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Calc ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "053f79f3-e571-4fbc-857f-55088c9570fb",
            "sourceColumn": "Calc ID",
            "summarizeBy": "count"
          },
          {
            "name": "Calc Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0178f0c0-d57a-40bb-b5f0-ef59506e594e",
            "sortByColumn": "Calc ID",
            "sourceColumn": "Calc Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9944e7ee-91ee-4461-8eac-15c1dfd66dd8",
        "measures": [
          {
            "name": "Selected Calc",
            "expression": "MIN('@KPI Calc Type'[Calc ID])",
            "formatString": "0",
            "lineageTag": "f731f3c8-b4fb-482f-a75c-59ec914b555e"
          }
        ],
        "partitions": [
          {
            "name": "@KPI Calc Type",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUYpMTSzSLcnXTUksSVWK1YlWMgIK+iQWlygYGink5ueVZBQrxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Calc ID\" = _t, #\"Calc Type\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Calc ID\", Int64.Type}, {\"Calc Type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "@DT Granularity",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "abd0ce9e989e494eb2ae5dfef01962bf"
          }
        ],
        "columns": [
          {
            "name": "@DT Granularity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8396a2c2-e87d-4d33-bbe5-2aa7ab282fe9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "@DT Granularity Fields"
                }
              ]
            },
            "sortByColumn": "@DT Granularity Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "@DT Granularity Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4cc64e0a-1340-4676-9caf-b2aec23bfdec",
            "sortByColumn": "@DT Granularity Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "@DT Granularity Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ceb6426c-86e1-4531-89ac-cd75be090855",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Granularity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'@DT Granularity'[@DT Granularity]",
            "isDataTypeInferred": true,
            "lineageTag": "9f1f25c9-5aad-4b1f-9cb1-825169b79b74",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "61b71c59-6cc0-47cf-b882-4208a165e443",
        "partitions": [
          {
            "name": "@DT Granularity",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Year\", NAMEOF('DIM Date'[Year]), 0),",
                "    (\"Quarter\", NAMEOF('DIM Date'[Quarter Year]), 1),",
                "    (\"Month\", NAMEOF('DIM Date'[Month Year]), 2),",
                "    (\"Date\", NAMEOF('DIM Date'[Date]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "@MA Periods",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "be4e59ee6c754430bcb51eab55fd6fd2"
          }
        ],
        "columns": [
          {
            "name": "@MA Periods",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "689defb3-9b41-40a9-a74c-84902db7a7be",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8a030cf1-b84d-4003-ad21-b836174f0eab",
        "measures": [
          {
            "name": "@MA Periods Value",
            "expression": "SELECTEDVALUE('@MA Periods'[@MA Periods])",
            "formatString": "0",
            "lineageTag": "2f7ed630-63ec-4475-ba8d-92942e4577ab"
          }
        ],
        "partitions": [
          {
            "name": "@MA Periods",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 30, 1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}